<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from org.civicoop.civirules/xml/schema/CRM/Civirules/RuleAction.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:77414701b7fb43e79dc18b6785f37b74)
 */
use CRM_Civirules_ExtensionUtil as E;

/**
 * Database access object for the CiviRulesRuleAction entity.
 */
class CRM_Civirules_DAO_CiviRulesRuleAction extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civirule_rule_action';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique RuleAction ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $rule_id;

  /**
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $action_id;

  /**
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $action_params;

  /**
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $delay;

  /**
   * @var int|string|null
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $ignore_condition_with_delay;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civirule_rule_action';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Civi Rules Rule Actions') : E::ts('Civi Rules Rule Action');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique RuleAction ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civirule_rule_action.id',
          'table_name' => 'civirule_rule_action',
          'entity' => 'CiviRulesRuleAction',
          'bao' => 'CRM_Civirules_DAO_CiviRulesRuleAction',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'rule_id' => [
          'name' => 'rule_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Rule ID'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civirule_rule_action.rule_id',
          'default' => NULL,
          'table_name' => 'civirule_rule_action',
          'entity' => 'CiviRulesRuleAction',
          'bao' => 'CRM_Civirules_DAO_CiviRulesRuleAction',
          'localizable' => 0,
          'FKClassName' => 'CRM_Civirules_DAO_CiviRulesRule',
          'add' => NULL,
        ],
        'action_id' => [
          'name' => 'action_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Action ID'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civirule_rule_action.action_id',
          'default' => NULL,
          'table_name' => 'civirule_rule_action',
          'entity' => 'CiviRulesRuleAction',
          'bao' => 'CRM_Civirules_DAO_CiviRulesRuleAction',
          'localizable' => 0,
          'FKClassName' => 'CRM_Civirules_DAO_CiviRulesAction',
          'add' => NULL,
        ],
        'action_params' => [
          'name' => 'action_params',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Action Params'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civirule_rule_action.action_params',
          'default' => NULL,
          'table_name' => 'civirule_rule_action',
          'entity' => 'CiviRulesRuleAction',
          'bao' => 'CRM_Civirules_DAO_CiviRulesRuleAction',
          'localizable' => 0,
          'add' => NULL,
        ],
        'delay' => [
          'name' => 'delay',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Delay'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civirule_rule_action.delay',
          'default' => NULL,
          'table_name' => 'civirule_rule_action',
          'entity' => 'CiviRulesRuleAction',
          'bao' => 'CRM_Civirules_DAO_CiviRulesRuleAction',
          'localizable' => 0,
          'add' => NULL,
        ],
        'ignore_condition_with_delay' => [
          'name' => 'ignore_condition_with_delay',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Ignore Condition With Delay'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civirule_rule_action.ignore_condition_with_delay',
          'default' => '0',
          'table_name' => 'civirule_rule_action',
          'entity' => 'CiviRulesRuleAction',
          'bao' => 'CRM_Civirules_DAO_CiviRulesRuleAction',
          'localizable' => 0,
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Enabled'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civirule_rule_action.is_active',
          'default' => '1',
          'table_name' => 'civirule_rule_action',
          'entity' => 'CiviRulesRuleAction',
          'bao' => 'CRM_Civirules_DAO_CiviRulesRuleAction',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
            'label' => E::ts("Enabled"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, '_rule_action', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, '_rule_action', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
